begin;

with upserted_set as (
  insert into public.hoops_card_sets (slug, name, release_year)
  values ('2025-26-topps-nba-hoops-basketball', '2025-26 Topps NBA Hoops Basketball', '2025-26')
  on conflict (slug) do update
    set name = excluded.name, release_year = excluded.release_year
  returning id
)
insert into public.hoops_cards (set_id, category, subset, card_number, player_name, team_name)
select upserted_set.id, seed.category, seed.subset, seed.card_number, seed.player_name, seed.team_name
from upserted_set
cross join (values
  ('Base', 'Base Set', '1', 'Rui Hachimura', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '2', 'Saddiq Bey', 'Washington Wizards'),
  ('Base', 'Base Set', '3', 'OG Anunoby', 'New York Knicks'),
  ('Base', 'Base Set', '4', 'Tyler Herro', 'Miami Heat'),
  ('Base', 'Base Set', '5', 'Deandre Ayton', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '6', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '7', 'Dylan Harper', 'San Antonio Spurs'),
  ('Base', 'Base Set', '8', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '9', 'Joel Embiid', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '10', 'Pascal Siakam', 'Indiana Pacers'),
  ('Base', 'Base Set', '11', 'Myles Turner', 'Indiana Pacers'),
  ('Base', 'Base Set', '12', 'Kam Jones', 'Indiana Pacers'),
  ('Base', 'Base Set', '13', 'Jalen Suggs', 'Orlando Magic'),
  ('Base', 'Base Set', '14', 'Austin Reaves', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '15', 'Brandon Williams', 'Dallas Mavericks'),
  ('Base', 'Base Set', '16', 'Malik Beasley', 'Detroit Pistons'),
  ('Base', 'Base Set', '17', 'Koby Brea', 'Phoenix Suns'),
  ('Base', 'Base Set', '18', 'De''Aaron Fox', 'San Antonio Spurs'),
  ('Base', 'Base Set', '19', 'Jamir Watkins', 'Washington Wizards'),
  ('Base', 'Base Set', '20', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '21', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '22', 'Marcus Smart', 'Washington Wizards'),
  ('Base', 'Base Set', '23', 'Keldon Johnson', 'San Antonio Spurs'),
  ('Base', 'Base Set', '24', 'Alex Caruso', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '25', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Base', 'Base Set', '26', 'Naz Reid', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '27', 'Max Strus', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '28', 'Evan Mobley', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '29', 'Nic Claxton', 'Brooklyn Nets'),
  ('Base', 'Base Set', '30', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Base', 'Base Set', '31', 'Ivica Zubac', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '32', 'Alijah Martin', 'Toronto Raptors'),
  ('Base', 'Base Set', '33', 'AJ Green', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '34', 'Al Horford', 'Boston Celtics'),
  ('Base', 'Base Set', '35', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Base', 'Base Set', '36', 'Onyeka Okungwu', 'Atlanta Hawks'),
  ('Base', 'Base Set', '37', 'Bam Adebayo', 'Miami Heat'),
  ('Base', 'Base Set', '38', 'Ace Bailey', 'Utah Jazz'),
  ('Base', 'Base Set', '39', 'Jrue Holiday', 'Boston Celtics'),
  ('Base', 'Base Set', '40', 'Franz Wagner', 'Orlando Magic'),
  ('Base', 'Base Set', '41', 'Donte DiVincenzo', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '42', 'Gary Payton II', 'Golden State Warriors'),
  ('Base', 'Base Set', '43', 'Reed Sheppard', 'Houston Rockets'),
  ('Base', 'Base Set', '44', 'Larry Nance Jr.', 'Atlanta Hawks'),
  ('Base', 'Base Set', '45', 'Keyonte George', 'Utah Jazz'),
  ('Base', 'Base Set', '46', 'Devin Carter', 'Sacramento Kings'),
  ('Base', 'Base Set', '47', 'Stephon Castle', 'San Antonio Spurs'),
  ('Base', 'Base Set', '48', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '49', 'Josh Giddey', 'Chicago Bulls'),
  ('Base', 'Base Set', '50', 'Jalen Johnson', 'Atlanta Hawks'),
  ('Base', 'Base Set', '51', 'Andrew Nembhard', 'Indiana Pacers'),
  ('Base', 'Base Set', '52', 'Asa Newell', 'Atlanta Hawks'),
  ('Base', 'Base Set', '53', 'Devin Booker', 'Phoenix Suns'),
  ('Base', 'Base Set', '54', 'Quentin Grimes', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '55', 'Jamal Murray', 'Denver Nuggets'),
  ('Base', 'Base Set', '56', 'Kyshawn George', 'Washington Wizards'),
  ('Base', 'Base Set', '57', 'Ryan Dunn', 'Phoenix Suns'),
  ('Base', 'Base Set', '58', 'Alex Sarr', 'Washington Wizards'),
  ('Base', 'Base Set', '59', 'Ben Saraf', 'Brooklyn Nets'),
  ('Base', 'Base Set', '60', 'Andre Drummond', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '61', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '62', 'Derik Queen', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '63', 'Steven Adams', 'Houston Rockets'),
  ('Base', 'Base Set', '64', 'Jakob Poeltl', 'Toronto Raptors'),
  ('Base', 'Base Set', '65', 'Coby White', 'Chicago Bulls'),
  ('Base', 'Base Set', '66', 'Khaman Maluach', 'Phoenix Suns'),
  ('Base', 'Base Set', '67', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Base', 'Base Set', '68', 'Bennedict Mathurin', 'Indiana Pacers'),
  ('Base', 'Base Set', '69', 'DeMar DeRozan', 'Sacramento Kings'),
  ('Base', 'Base Set', '70', 'Noa Essengue', 'Chicago Bulls'),
  ('Base', 'Base Set', '71', 'James Harden', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '72', 'Hugo González', 'Boston Celtics'),
  ('Base', 'Base Set', '73', 'Kawhi Leonard', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '74', 'Will Riley', 'Washington Wizards'),
  ('Base', 'Base Set', '75', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Base', 'Base Set', '76', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '77', 'Cole Anthony', 'Orlando Magic'),
  ('Base', 'Base Set', '78', 'Trey Murphy III', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '79', 'Bobby Portis', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '80', 'Brandon Miller', 'Charlotte Hornets'),
  ('Base', 'Base Set', '81', 'Cade Cunningham', 'Detroit Pistons'),
  ('Base', 'Base Set', '82', 'Nikola Jokić', 'Denver Nuggets'),
  ('Base', 'Base Set', '83', 'Keegan Murray', 'Sacramento Kings'),
  ('Base', 'Base Set', '84', 'LeBron James', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '85', 'Scoot Henderson', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '86', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '87', 'Matisse Thybulle', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '88', 'Thomas Sorber', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '89', 'Deni Avdija', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '90', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '91', 'Andrew Wiggins', 'Miami Heat'),
  ('Base', 'Base Set', '92', 'Taurean Prince', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '93', 'Drake Powell', 'Brooklyn Nets'),
  ('Base', 'Base Set', '94', 'Jaden McDaniels', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '95', 'Anfernee Simons', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '96', 'Jaylen Wells', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '97', 'Brandin Podziemski', 'Golden State Warriors'),
  ('Base', 'Base Set', '98', 'Lonzo Ball', 'Chicago Bulls'),
  ('Base', 'Base Set', '99', 'Jalen Duren', 'Detroit Pistons'),
  ('Base', 'Base Set', '100', 'Mikal Bridges', 'New York Knicks'),
  ('Base', 'Base Set', '101', 'Jae Crowder', 'Sacramento Kings'),
  ('Base', 'Base Set', '102', 'Jalen Green', 'Houston Rockets'),
  ('Base', 'Base Set', '103', 'Ronald Holland II', 'Detroit Pistons'),
  ('Base', 'Base Set', '104', 'Klay Thompson', 'Dallas Mavericks'),
  ('Base', 'Base Set', '105', 'Zaccharie Risacher', 'Atlanta Hawks'),
  ('Base', 'Base Set', '106', 'Jaxson Hayes', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '107', 'Dereck Lively II', 'Dallas Mavericks'),
  ('Base', 'Base Set', '108', 'Anthony Davis', 'Dallas Mavericks'),
  ('Base', 'Base Set', '109', 'Dyson Daniels', 'Atlanta Hawks'),
  ('Base', 'Base Set', '110', 'Donovan Clingan', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '111', 'Alperun Sengun', 'Houston Rockets'),
  ('Base', 'Base Set', '112', 'Brandon Clarke', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '113', 'Max Christie', 'Dallas Mavericks'),
  ('Base', 'Base Set', '114', 'Nikola Jović', 'Miami Heat'),
  ('Base', 'Base Set', '115', 'Sam Hauser', 'Boston Celtics'),
  ('Base', 'Base Set', '116', 'Mark Williams', 'Charlotte Hornets'),
  ('Base', 'Base Set', '117', 'Anthony Black', 'Orlando Magic'),
  ('Base', 'Base Set', '118', 'Jimmy Butler III', 'Golden State Warriors'),
  ('Base', 'Base Set', '119', 'Lauri Markkanen', 'Utah Jazz'),
  ('Base', 'Base Set', '120', 'Draymond Green', 'Golden State Warriors'),
  ('Base', 'Base Set', '121', 'Cody Williams', 'Utah Jazz'),
  ('Base', 'Base Set', '122', 'Gary Trent Jr.', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '123', 'Amen Thompson', 'Houston Rockets'),
  ('Base', 'Base Set', '124', 'Josh Hart', 'New York Knicks'),
  ('Base', 'Base Set', '125', 'RJ Barrett', 'Toronto Raptors'),
  ('Base', 'Base Set', '126', 'Darius Garland', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '127', 'Tre Mann', 'Charlotte Hornets'),
  ('Base', 'Base Set', '128', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Base', 'Base Set', '129', 'Alex Toohey', 'Golden State Warriors'),
  ('Base', 'Base Set', '130', 'Paul George', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '131', 'Nick Smith Jr.', 'Charlotte Hornets'),
  ('Base', 'Base Set', '132', 'Noah Penda', 'Orlando Magic'),
  ('Base', 'Base Set', '133', 'Nolan Traore', 'Brooklyn Nets'),
  ('Base', 'Base Set', '134', 'Nickeil Alexander-Walker', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '135', 'Jaylen Brown', 'Boston Celtics'),
  ('Base', 'Base Set', '136', 'Damian Lillard', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '137', 'Miles McBride', 'New York Knicks'),
  ('Base', 'Base Set', '138', 'Xavier Tillman', 'Boston Celtics'),
  ('Base', 'Base Set', '139', 'Jordan Hawkins', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '140', 'Zach LaVine', 'Sacramento Kings'),
  ('Base', 'Base Set', '141', 'Stephen Curry', 'Golden State Warriors'),
  ('Base', 'Base Set', '142', 'Jase Richardson', 'Orlando Magic'),
  ('Base', 'Base Set', '143', 'Christian Braun', 'Denver Nuggets'),
  ('Base', 'Base Set', '144', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Base', 'Base Set', '145', 'Harrison Barnes', 'San Antonio Spurs'),
  ('Base', 'Base Set', '146', 'Aaron Gordon', 'Denver Nuggets'),
  ('Base', 'Base Set', '147', 'T.J. McConnell', 'Indiana Pacers'),
  ('Base', 'Base Set', '148', 'Mitchell Robinson', 'New York Knicks'),
  ('Base', 'Base Set', '149', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Base', 'Base Set', '150', 'De''Andre Hunter', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '151', 'Sion James', 'Charlotte Hornets'),
  ('Base', 'Base Set', '152', 'Nicolas Batum', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '153', 'Naji Marshall', 'Dallas Mavericks'),
  ('Base', 'Base Set', '154', 'Jeremy Sochan', 'San Antonio Spurs'),
  ('Base', 'Base Set', '155', 'Julian Phillips', 'Chicago Bulls'),
  ('Base', 'Base Set', '156', 'Matas Buzelis', 'Chicago Bulls'),
  ('Base', 'Base Set', '157', 'Rudy Gobert', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '158', 'Brooks Barnhizer', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '159', 'Johni Broome', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '160', 'Rob Dillingham', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '161', 'Grant Williams', 'Charlotte Hornets'),
  ('Base', 'Base Set', '162', 'John Tonje', 'Utah Jazz'),
  ('Base', 'Base Set', '163', 'Scotty Pippen Jr.', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '164', 'Jamal Shead', 'Toronto Raptors'),
  ('Base', 'Base Set', '165', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '166', 'Immanuel Quickley', 'Toronto Raptors'),
  ('Base', 'Base Set', '167', 'Tobias Harris', 'Detroit Pistons'),
  ('Base', 'Base Set', '168', 'Walker Kessler', 'Utah Jazz'),
  ('Base', 'Base Set', '169', 'Rocco Zikarsky', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '170', 'Bilal Coulibaly', 'Washington Wizards'),
  ('Base', 'Base Set', '171', 'Jonas Valančiūnas', 'Washington Wizards'),
  ('Base', 'Base Set', '172', 'Kel''el Ware', 'Miami Heat'),
  ('Base', 'Base Set', '173', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Base', 'Base Set', '174', 'Kentavious Caldwell-Pope', 'Orlando Magic'),
  ('Base', 'Base Set', '175', 'Khris Middleton', 'Washington Wizards'),
  ('Base', 'Base Set', '176', 'Zach Collins', 'Chicago Bulls'),
  ('Base', 'Base Set', '177', 'Derrick White', 'Boston Celtics'),
  ('Base', 'Base Set', '178', 'Aaron Nesmith', 'Indiana Pacers'),
  ('Base', 'Base Set', '179', 'Kyle Filipowski', 'Utah Jazz'),
  ('Base', 'Base Set', '180', 'Gradey Dick', 'Toronto Raptors'),
  ('Base', 'Base Set', '181', 'Carter Bryant', 'San Antonio Spurs'),
  ('Base', 'Base Set', '182', 'Adou Thiero', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '183', 'Michael Porter Jr.', 'Denver Nuggets'),
  ('Base', 'Base Set', '184', 'Kyle Kuzma', 'Milwaukee Bucks'),
  ('Base', 'Base Set', '185', 'LaMelo Ball', 'Charlotte Hornets'),
  ('Base', 'Base Set', '186', 'Grayson Allen', 'Phoenix Suns'),
  ('Base', 'Base Set', '187', 'Jaden Ivey', 'Detroit Pistons'),
  ('Base', 'Base Set', '188', 'Jaren Jackson Jr.', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '189', 'P.J. Washington Jr.', 'Dallas Mavericks'),
  ('Base', 'Base Set', '190', 'Jalen Brunson', 'New York Knicks'),
  ('Base', 'Base Set', '191', 'Kris Murray', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '192', 'Jordan Clarkson', 'Utah Jazz'),
  ('Base', 'Base Set', '193', 'Julius Randle', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '194', 'Paolo Banchero', 'Orlando Magic'),
  ('Base', 'Base Set', '195', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Base', 'Base Set', '196', 'Isaiah Hartenstein', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '197', 'Jared McCain', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '198', 'Jarrett Allen', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '199', 'Fred VanVleet', 'Houston Rockets'),
  ('Base', 'Base Set', '200', 'CJ McCollum', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '201', 'Kristaps Porziņģis', 'Boston Celtics'),
  ('Base', 'Base Set', '202', 'Luguentz Dort', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '203', 'John Collins', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '204', 'Domantas Sabonis', 'Sacramento Kings'),
  ('Base', 'Base Set', '205', 'Malik Monk', 'Sacramento Kings'),
  ('Base', 'Base Set', '206', 'Jonathan Kuminga', 'Golden State Warriors'),
  ('Base', 'Base Set', '207', 'Ryan Kalkbrenner', 'Charlotte Hornets'),
  ('Base', 'Base Set', '208', 'Jabari Smith Jr.', 'Houston Rockets'),
  ('Base', 'Base Set', '209', 'Johnny Furphy', 'Indiana Pacers'),
  ('Base', 'Base Set', '210', 'Maxime Raynaud', 'Sacramento Kings'),
  ('Base', 'Base Set', '211', 'Cam Thomas', 'Brooklyn Nets'),
  ('Base', 'Base Set', '212', 'Jonathan Isaac', 'Orlando Magic'),
  ('Base', 'Base Set', '213', 'Payton Pritchard', 'Boston Celtics'),
  ('Base', 'Base Set', '214', 'Desmond Bane', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '215', 'Tyrese Proctor', 'Cleveland Cavaliers'),
  ('Base', 'Base Set', '216', 'Caris LeVert', 'Atlanta Hawks'),
  ('Base', 'Base Set', '217', 'DaRon Holmes II', 'Denver Nuggets'),
  ('Base', 'Base Set', '218', 'Chaz Lanier', 'Detroit Pistons'),
  ('Base', 'Base Set', '219', 'Cason Wallace', 'Oklahoma City Thunder'),
  ('Base', 'Base Set', '220', 'Ja Morant', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '221', 'Kevin Durant', 'Houston Rockets'),
  ('Base', 'Base Set', '222', 'Norman Powell', 'Miami Heat'),
  ('Base', 'Base Set', '223', 'Jaime Jaquez Jr.', 'Miami Heat'),
  ('Base', 'Base Set', '224', 'Brandon Ingram', 'Toronto Raptors'),
  ('Base', 'Base Set', '225', 'Obi Toppin', 'Indiana Pacers'),
  ('Base', 'Base Set', '226', 'Tre Johnson III', 'Washington Wizards'),
  ('Base', 'Base Set', '227', 'Dorian Finney-Smith', 'Los Angeles Lakers'),
  ('Base', 'Base Set', '228', 'Jayson Tatum', 'Boston Celtics'),
  ('Base', 'Base Set', '229', 'Micah Peavy', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '230', 'Zach Edey', 'Memphis Grizzlies'),
  ('Base', 'Base Set', '231', 'Dejounte Murray', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '232', 'Liam McNeeley', 'Charlotte Hornets'),
  ('Base', 'Base Set', '233', 'Devin Vassell', 'San Antonio Spurs'),
  ('Base', 'Base Set', '234', 'Scottie Barnes', 'Toronto Raptors'),
  ('Base', 'Base Set', '235', 'Cameron Johnson', 'Denver Nuggets'),
  ('Base', 'Base Set', '236', 'Bub Carrington', 'Washington Wizards'),
  ('Base', 'Base Set', '237', 'Kyle Lowry', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '238', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '239', 'Buddy Hield', 'Golden State Warriors'),
  ('Base', 'Base Set', '240', 'Ausar Thompson', 'Detroit Pistons'),
  ('Base', 'Base Set', '241', 'Nique Clifford', 'Sacramento Kings'),
  ('Base', 'Base Set', '242', 'Tristan da Silva', 'Orlando Magic'),
  ('Base', 'Base Set', '243', 'Shaedon Sharpe', 'Portland Trail Blazers'),
  ('Base', 'Base Set', '244', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '245', 'Patrick Williams', 'Chicago Bulls'),
  ('Base', 'Base Set', '246', 'Danny Wolf', 'Brooklyn Nets'),
  ('Base', 'Base Set', '247', 'Chris Paul', 'San Antonio Spurs'),
  ('Base', 'Base Set', '248', 'Jae''Sean Tate', 'Houston Rockets'),
  ('Base', 'Base Set', '249', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Base', 'Base Set', '250', 'Russell Westbrook', 'Denver Nuggets'),
  ('Base', 'Base Set', '251', 'Bruce Brown', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '252', 'Ayo Dosunmu', 'Chicago Bulls'),
  ('Base', 'Base Set', '253', 'Oso Ighodaro', 'Phoenix Suns'),
  ('Base', 'Base Set', '254', 'Bradley Beal', 'Phoenix Suns'),
  ('Base', 'Base Set', '255', 'Rasheer Fleming', 'Phoenix Suns'),
  ('Base', 'Base Set', '256', 'Derrick Jones Jr.', 'Los Angeles Clippers'),
  ('Base', 'Base Set', '257', 'Herbert Jones', 'New Orleans Pelicans'),
  ('Base', 'Base Set', '258', 'Tyrese Maxey', 'Philadelphia 76ers'),
  ('Base', 'Base Set', '259', 'Trae Young', 'Atlanta Hawks'),
  ('Base', 'Base Set', '260', 'Dalton Knecht', 'Los Angeles Lakers'),
  ('Base', 'Base - Highlights', '261', 'Stephen Curry', 'Golden State Warriors'),
  ('Base', 'Base - Highlights', '262', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Base', 'Base - Highlights', '263', 'Jayson Tatum', 'Boston Celtics'),
  ('Base', 'Base - Highlights', '264', 'Ja Morant', 'Memphis Grizzlies'),
  ('Base', 'Base - Highlights', '265', 'Pascal Siakam', 'Indiana Pacers'),
  ('Base', 'Base - Highlights', '266', 'Aaron Gordon', 'Denver Nuggets'),
  ('Base', 'Base - Highlights', '267', 'Shaedon Sharpe', 'Portland Trail Blazers'),
  ('Base', 'Base - Highlights', '268', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Base', 'Base - Highlights', '269', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Base', 'Base - Highlights', '270', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Base', 'Base - All-Stars', '271', 'Jaylen Brown', 'Boston Celtics'),
  ('Base', 'Base - All-Stars', '272', 'Kevin Durant', 'Phoenix Suns'),
  ('Base', 'Base - All-Stars', '273', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Base', 'Base - All-Stars', '274', 'Damian Lillard', 'Milwaukee Bucks'),
  ('Base', 'Base - All-Stars', '275', 'Stephen Curry', 'Golden State Warriors'),
  ('Base', 'Base - All-Stars', '276', 'James Harden', 'Los Angeles Clippers'),
  ('Base', 'Base - All-Stars', '277', 'Jayson Tatum', 'Boston Celtics'),
  ('Base', 'Base - All-Stars', '278', 'Jalen Brunson', 'New York Knicks'),
  ('Base', 'Base - All-Stars', '279', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Base', 'Base - All-Stars', '280', 'Tyler Herro', 'Miami Heat'),
  ('Base', 'Base - All-Stars', '281', 'Evan Mobley', 'Cleveland Cavaliers'),
  ('Base', 'Base - All-Stars', '282', 'Cade Cunningham', 'Detroit Pistons'),
  ('Base', 'Base - All-Stars', '283', 'Darius Garland', 'Cleveland Cavaliers'),
  ('Base', 'Base - All-Stars', '284', 'Jaren Jackson Jr.', 'Memphis Grizzlies'),
  ('Base', 'Base - All-Stars', '285', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Base', 'Base - All-Stars', '286', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Base', 'Base - All-Stars', '287', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Base', 'Base - All-Stars', '288', 'Pascal Siakam', 'Indiana Pacers'),
  ('Base', 'Base - All-Stars', '289', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Base', 'Base - All-Stars', '290', 'Nikola Jokić', 'Denver Nuggets'),
  ('Base', 'Base - All-Stars', '291', 'Alperen Sengun', 'Houston Rockets'),
  ('Base', 'Base - All-Stars', '292', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Base', 'Base - All-Stars', '293', 'Trae Young', 'Atlanta Hawks'),
  ('Base', 'Base - All-Stars', '294', 'Stephon Castle', 'San Antonio Spurs'),
  ('Base', 'Base - All-Stars', '295', 'Jaylen Wells', 'Memphis Grizzlies'),
  ('Base', 'Base - All-Stars', '296', 'Zach Edey', 'Memphis Grizzlies'),
  ('Base', 'Base - All-Stars', '297', 'Ryan Dunn', 'Phoenix Suns'),
  ('Base', 'Base - All-Stars', '298', 'Dalton Knecht', 'Los Angeles Lakers'),
  ('Base', 'Base - All-Stars', '299', 'Keyonte George', 'Utah Jazz'),
  ('Base', 'Base - All-Stars', '300', 'Amen Thompson', 'Houston Rockets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-AB', 'Ace Bailey', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-AM', 'Alijah Martin', 'Toronto Raptors'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-AN', 'Asa Newell', 'Atlanta Hawks'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-AT', 'Adou Thiero', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-ATO', 'Alex Toohey', 'Golden State Warriors'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-BB', 'Brooks Barnhizer', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-BS', 'Ben Saraf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-CC', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-CF', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-CL', 'Chaz Lanier', 'Detroit Pistons'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-CM', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-DH', 'Dylan Harper', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-DP', 'Drake Powell', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-DQ', 'Derik Queen', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-DW', 'Danny Wolf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-ED', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JB', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JBR', 'Johni Broome', 'Philadelphia 76ers'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JR', 'Jase Richardson', 'Orlando Magic'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JS', 'Javon Small', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JT', 'John Tonje', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-JW', 'Jamir Watkins', 'Washington Wizards'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-KJ', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-KK', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-KM', 'Khaman Maluach', 'Phoenix Suns'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-KS', 'Kobe Sanders', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-LM', 'Liam McNeeley', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-MR', 'Maxime Raynaud', 'Sacramento Kings'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-NC', 'Nique Clifford', 'Sacramento Kings'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-NE', 'Noa Essengue', 'Chicago Bulls'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-NT', 'Nolan Traore', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-RF', 'Rasheer Fleming', 'Phoenix Suns'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-RK', 'Ryan Kalkbrenner', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-SJ', 'Sion James', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-TP', 'Tyrese Proctor', 'Cleveland Cavaliers'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-TS', 'Thomas Sorber', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-WC', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-WR', 'Will Riley', 'Washington Wizards'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-YH', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Rookie Signatures', 'HRS-YK', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Signs', 'HS-AE', 'Alex English', 'Denver Nuggets'),
  ('Autographs', 'Hoops Signs', 'HS-AED', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Signs', 'HS-AH', 'Al Horford', 'Boston Celtics'),
  ('Autographs', 'Hoops Signs', 'HS-AM', 'Ajay Mitchell', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Signs', 'HS-BC', 'Brandon Clarke', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Signs', 'HS-BM', 'Brandon Miller', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Signs', 'HS-CJ', 'Cameron Johnson', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Signs', 'HS-DD', 'Donte DiVincenzo', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Signs', 'HS-DG', 'Daniel Gafford', 'Dallas Mavericks'),
  ('Autographs', 'Hoops Signs', 'HS-DJ', 'Derrick Jones Jr.', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Signs', 'HS-DR', 'Duncan Robinson', 'Miaimi Heat'),
  ('Autographs', 'Hoops Signs', 'HS-GD', 'Gradey Dick', 'Toronto Raptors'),
  ('Autographs', 'Hoops Signs', 'HS-GG', 'George Gervin', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Signs', 'HS-GV', 'Gabe Vincent', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops Signs', 'HS-HJ', 'Herbert Jones', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Signs', 'HS-JAW', 'Jalen Wilson', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Signs', 'HS-JH', 'Juwan Howard', 'Washington Wizards'),
  ('Autographs', 'Hoops Signs', 'HS-JJ', 'Jaime Jaquez Jr.', 'Miami Heat'),
  ('Autographs', 'Hoops Signs', 'HS-JS', 'Jamal Shead', 'Toronto Raptors'),
  ('Autographs', 'Hoops Signs', 'HS-JT', 'Jaylon Tyson', 'Cleveland Cavaliers'),
  ('Autographs', 'Hoops Signs', 'HS-JW', 'Jaylen Wells', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Signs', 'HS-JWI', 'Jason Williams', 'Sacramento Kings'),
  ('Autographs', 'Hoops Signs', 'HS-KF', 'Kyle Filipowski', 'Utah Jazz'),
  ('Autographs', 'Hoops Signs', 'HS-KG', 'Kyshawn George', 'Washington Wizards'),
  ('Autographs', 'Hoops Signs', 'HS-KH', 'Kevin Huerter', 'Chicago Bulls'),
  ('Autographs', 'Hoops Signs', 'HS-KM', 'Kris Murray', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Signs', 'HS-KW', 'Kel''el ware', 'Miami Heat'),
  ('Autographs', 'Hoops Signs', 'HS-LHU', 'Larry Hughes', 'Washington Wizards'),
  ('Autographs', 'Hoops Signs', 'HS-LJ', 'Larry Johnson', 'New York Knicks'),
  ('Autographs', 'Hoops Signs', 'HS-MS', 'Marcus Sasser', 'Detroit Pistons'),
  ('Autographs', 'Hoops Signs', 'HS-MST', 'Max Strus', 'Cleveland Cavaliers'),
  ('Autographs', 'Hoops Signs', 'HS-NENE', 'Nenê', 'Denver Nuggets'),
  ('Autographs', 'Hoops Signs', 'HS-NJ', 'Nikola Jokić', 'Denver Nuggets'),
  ('Autographs', 'Hoops Signs', 'HS-PD', 'Pacôme Dadiet', 'New York Knicks'),
  ('Autographs', 'Hoops Signs', 'HS-PL', 'Pelle Larsson', 'Miami Heat'),
  ('Autographs', 'Hoops Signs', 'HS-PP', 'Payton Pritchard', 'Boston Celtics'),
  ('Autographs', 'Hoops Signs', 'HS-PS', 'Peja Stojakovic', 'Sacramento Kings'),
  ('Autographs', 'Hoops Signs', 'HS-QP', 'Quinten Post', 'Golden State Warriors'),
  ('Autographs', 'Hoops Signs', 'HS-RD', 'Ryan Dunn', 'Phoenix Suns'),
  ('Autographs', 'Hoops Signs', 'HS-RH', 'Ronald Holland II', 'Detroit Pistons'),
  ('Autographs', 'Hoops Signs', 'HS-RHO', 'Robert Horry', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops Signs', 'HS-RJ', 'Richard Jefferson', 'New Jersey Nets'),
  ('Autographs', 'Hoops Signs', 'HS-RR', 'Rayan Rupert', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Signs', 'HS-SFR', 'Steve Francis', 'Houston Rockets'),
  ('Autographs', 'Hoops Signs', 'HS-SGA', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Signs', 'HS-TK', 'Tyler Kolek', 'New York Knicks'),
  ('Autographs', 'Hoops Signs', 'HS-TMU', 'Trey Murphy III', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Signs', 'HS-TS', 'Terrence Shannon Jr.', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Signs', 'HS-Td', 'Tristan da Silva', 'Orlando Magic'),
  ('Autographs', 'Hoops Signs', 'HS-UH', 'Udonis Haslem', 'Miami Heat'),
  ('Autographs', 'Hoops Signs', 'HS-VW', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Signs', 'HS-YM', 'Yves Missi', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Signs', 'HS-ZE', 'Zach Edey', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Signs', 'HS-CK', 'Corey Kispert', 'Washington Wizards'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-AL', 'Liam McNeeley/Asa Newell', 'Charlotte Hornets/Atlanta Hawks'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-ALA', 'Alex Toohey/Lachlan Olbrich', 'Golden State Warriors/Chicago Bulls'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-AM', 'Amari Williams/Max Shulga', 'Boston Celtics'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-AW', 'Walter Clayton Jr./Ace Bailey', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-AWI', 'Will Richard/Alex Toohey', 'Golden State Warriors'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-BD', 'Danny Wolf/Ben Saraf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-CD', 'Dylan Harper/Cooper Flagg', 'San Antonio Spurs/Dallas Mavericks'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-CK', 'Kon Knueppel/Cooper Flagg', 'Charlotte Hornets/Dallas Mavericks'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-CN', 'Noa Essengue/Collin Murray-Boyles', 'Chicago Bulls/Toronto Raptors'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-CNI', 'Nique Clifford/Cedric Coward', 'Sacramento Kings/Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-DA', 'Ace Bailey/Dylan Harper', 'Utah Jazz/San Antonio Spurs'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-DAS', 'Asa Newell/Derik Queen', 'Atlanta Hawks/New Orleans Pelicans'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-DJ', 'Drake Powell/Jase Richardson', 'Brooklyn Nets/Orlando Magic'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-EN', 'Egor Dëmin/Nolan Traore', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-KD', 'Khaman Maluach/Derik Queen', 'Phoenix Suns/New Orleans Pelicans'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-KL', 'Liam McNeeley/Kon Knueppel', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-KT', 'Tyrese Proctor/Khaman Maluach', 'Cleveland Cavaliers/Phoenix Suns'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-KTA', 'Taelon Peter/Kam Jones', 'Indiana Pacers'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-KW', 'Will Riley/Kasparas Jakučionis', 'Washington Wizards/Miami Heat'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-RN', 'Rasheer Fleming/Noah Penda', 'Phoenix Suns/Orlando Magic'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-SR', 'Sion James/Ryan Kalkbrenner', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-TB', 'Thomas Sorber/Brooks Barnhizer', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-WA', 'Walter Clayton Jr./Alijah Martin', 'Utah Jazz/Toronto Raptors'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-YJ', 'Yang Hansen/Joan Beringer', 'Portland Trail Blazers/Minnesota Timberwolves'),
  ('Autographs', 'Hoops Rookie Duals', 'HRD-YK', 'Kobe Sanders/Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-AEG', 'Egor Dëmin/Collin Murray-Boyles/Ace Bailey', 'Brooklyn Nets/Toronto Raptors/Utah Jazz'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-CDA', 'Dylan Harper/Cooper Flagg/Ace Bailey', 'San Antonio Spurs/Dallas Mavericks/Utah Jazz'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-CDK', 'Cooper Flagg/Dylan Harper/Kon Knueppel', 'Dallas Mavericks/San Antonio Spurs/Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-DAL', 'Derik Queen/Asa Newell/Liam McNeeley', 'New Orleans Pelicans/Atlanta Hawks/Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-DBD', 'Ben Saraf/Drake Powell/Danny Wolf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-DKK', 'Kon Knueppel/Cooper Flagg/Khaman Maluach', 'Charlotte Hornets/Dallas Mavericks/Phoenix Suns'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-KJT', 'Tyrese Proctor/Jase Richardson/Kasparas Jakučionis', 'Cleveland Cavaliers/Orlando Magic/Miami Heat'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-NJN', 'Joan Beringer/Nolan Traore/Noa Essengue', 'Minnesota Timberwolves/Brooklyn Nets/Chicago Bulls'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-NWA', 'Will Riley/Nique Clifford/Adou Thiero', 'Washington Wizards/Sacramento Kings/Los Angeles Lakers'),
  ('Autographs', 'Hoops Rookie Triples', 'HRT-WCA', 'Chaz Lanier/Walter Clayton Jr./Alijah Martin', 'Detroit Pistons/Utah Jazz/Toronto Raptors'),
  ('Autographs', 'Hoops Rookie/Veteran Duals', 'RVD-CG', 'Collin Murray-Boyles/Gradey Dick', 'Toronto Raptors'),
  ('Autographs', 'Hoops Rookie/Veteran Duals', 'RVD-CL', 'Dirk Nowitzki/Cooper Flagg', 'Dallas Mavericks'),
  ('Autographs', 'Hoops Rookie/Veteran Duals', 'RVD-DS', 'Stephon Castle/Dylan Harper', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Rookie/Veteran Duals', 'RVD-KB', 'Brandon Miller/Kon Knueppel', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie/Veteran Duals', 'RVD-KR', 'Khaman Maluach/Rudy Gobert', 'Phoenix Suns/Minnesota Timberwolves'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AB', 'Ace Bailey', 'Utah Jazz'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AFA', 'Al-Farouq Aminu', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AH', 'Al Horford', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AI', 'Allen Iverson', 'Philadelphia 76ers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AJ', 'AJ Johnson', 'Washington Wizards'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AN', 'Asa Newell', 'Atlanta Hawks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-AW', 'Amari Williams', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-CD', 'Clyde Drexler', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-CF', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-CH', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DC', 'Devin Carter', 'Sacramento Kings'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DH', 'Dylan Harper', 'San Antonio Spurs'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DM', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DN', 'Dirk Nowitzki', 'Dallas Mavericks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DR', 'David Robinson', 'San Antonio Spurs'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DRO', 'Dennis Rodman', 'Chicago Bulls'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-DW', 'Danny Wolf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-EH', 'Elvin Hayes', 'Houston Rockets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-HO', 'Hakeem Olajuwon', 'Houston Rockets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-IS', 'Isaiah Stewart', 'Detroit Pistons'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JH', 'James Harden', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JJB', 'JJ Barea', 'Dallas Mavericks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JM', 'Jahmai Mashack', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JS', 'Jerry Stackhouse', 'Detroit Pistons'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JSO', 'Jeremy Sochan', 'San Antonio Spurs'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-JT', 'Jayson Tatum', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KB', 'Koby Brea', 'Phoenix Suns'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KD', 'Kevin Durant', 'Houston Rockets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KJ', 'Kam Jones', 'Indiana Pacers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KK', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KM', 'Khaman Maluach', 'Phoenix Suns'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KMS', 'Kenyon Martin Sr.', 'New Jersey Nets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-KT', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-LB', 'Larry Bird', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-LJ', 'LeBron James', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-LMC', 'Liam McNeeley', 'Charlotte Hornets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-LO', 'Lachlan Olbrich', 'Chicago Bulls'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MB', 'Mikal Bridges', 'New York Knicks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MJ', 'Magic Johnson', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MJA', 'Mark Jackson', 'New York Knicks'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MP', 'Michael Porter Jr.', 'Denver Nuggets'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MPE', 'Micah Peavy', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MS', 'Marcus Smart', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MSH', 'Max Shulga', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-MW', 'Metta World Peace', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-NB', 'Nicolas Batum', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-NE', 'Noa Essengue', 'Chicago Bulls'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-NP', 'Noah Penda', 'Orlando Magic'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-PB', 'Paolo Banchero', 'Orlando Magic'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-PP', 'Paul Pierce', 'Boston Celtics'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-SB', 'Saddiq Bey', 'Washington Wizards'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-SC', 'Stephen Curry', 'Golden State Warriors'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-SO', 'Shaquille O''Neal', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-TM', 'Tracy McGrady', 'Toronto Raptors'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-TP', 'Taelon Peter', 'Indiana Pacers'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-VC', 'Vince Carter', 'Toronto Raptors'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-WC', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-WR', 'Will Richard', 'Golden State Warriors'),
  ('Autographs', 'Hoops 1989 Signatures', '89S-ZR', 'Zach Randolph', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-AB', 'Ace Bailey', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-AM', 'Alijah Martin', 'Toronto Raptors'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-AN', 'Asa Newell', 'Atlanta Hawks'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-AT', 'Adou Thiero', 'Los Angeles Lakers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-ATO', 'Alex Toohey', 'Golden State Warriors'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-AW', 'Amari Williams', 'Boston Celtics'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-BB', 'Brooks Barnhizer', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-BS', 'Ben Saraf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-CC', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-CF', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-CL', 'Chaz Lanier', 'Detroit Pistons'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-CM', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-DH', 'Dylan Harper', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-DP', 'Drake Powell', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-DQ', 'Derik Queen', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-DW', 'Danny Wolf', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-ED', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JB', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JBR', 'Johni Broome', 'Philadelphia 76ers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JM', 'Jahmai Mashack', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JR', 'Jase Richardson', 'Orlando Magic'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JS', 'Javon Small', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JT', 'John Tonje', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-JW', 'Jamir Watkins', 'Washington Wizards'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KB', 'Koby Brea', 'Phoenix Suns'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KJ', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KJO', 'Kam Jones', 'Indiana Pacers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KK', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KM', 'Khaman Maluach', 'Phoenix Suns'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-KS', 'Kobe Sanders', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-LM', 'Liam McNeeley', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-LO', 'Lachlan Olbrich', 'Chicago Bulls'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-MP', 'Micah Peavy', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-MR', 'Maxime Raynaud', 'Sacramento Kings'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-MS', 'Max Shulga', 'Boston Celtics'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-NC', 'Nique Clifford', 'Sacramento Kings'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-NE', 'Noa Essengue', 'Chicago Bulls'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-NP', 'Noah Penda', 'Orlando Magic'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-NT', 'Nolan Traore', 'Brooklyn Nets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-RF', 'Rasheer Fleming', 'Phoenix Suns'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-RK', 'Ryan Kalkbrenner', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-SJ', 'Sion James', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-TP', 'Tyrese Proctor', 'Cleveland Cavaliers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-TPE', 'Taelon Peter', 'Indiana Pacers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-TS', 'Thomas Sorber', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-WC', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-WR', 'Will Riley', 'Washington Wizards'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-WRI', 'Will Richard', 'Golden State Warriors'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-YH', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Rookie First Signs', 'HFS-YK', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-AB', 'Anthony Black', 'Orlando Magic'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-ABO', 'Adem Bona', 'Philadelphia 76ers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-AED', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-AJ', 'AJ Johnson', 'Washington Wizards'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-AJJ', 'Andre jackson Jr.', 'Milwaukee Bucks'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-AM', 'Ajay Mitchell', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-CC', 'Cam Christie', 'Los Angeles Clippers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-CS', 'Cam Spencer', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-CW', 'Cody Williams', 'Utah Jazz'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-DH', 'DaRon Holmes II', 'Denver Nuggets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-DJ', 'Dillon Jones', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-GD', 'Gradey Dick', 'Toronto Raptors'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-GJ', 'GG Jackson II', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-GN', 'Georges Niang', 'Atlanta Hawks'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JH', 'Jordan Hawkins', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JHO', 'Jett Howard', 'Orlando Magic'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JHS', 'Jalen Hood-Schifino', 'Philadelphia 76ers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JM', 'Jonathan Mogbo', 'Toronto Raptors'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JS', 'Jamal Shead', 'Toronto Raptors'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JT', 'Jayson Tatum', 'Boston Celtics'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JTA', 'Jae''Sean Tate', 'Houston Rockets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JW', 'Jarace Walker', 'Indiana Pacers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JWE', 'Jaylen Wells', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-JWI', 'Jaylin Williams', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-KD', 'Kevin Durant', 'Houston Rockets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-KM', 'Kevin McCullar Jr.', 'New York Knicks'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-MS', 'Marcus Sasser', 'Detroit Pistons'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-NJ', 'Nikola Jokić', 'Denver Nuggets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-NS', 'Nick Smith Jr.', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-NT', 'Nikola Topić', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-PL', 'Pelle Larsson', 'Miami Heat'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-QP', 'Quinten Post', 'Golden State Warriors'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-RH', 'Ronald Holland II', 'Detroit Pistons'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-RR', 'Rayan Rupert', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-SC', 'Stephen Curry', 'Golden State Warriors'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-SCA', 'Stephon Castle', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-SGA', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-SH', 'Scoot Henderson', 'Portland Trail Blazers'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-SP', 'Scotty Pippen Jr.', 'Memphis Grizzlies'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-TK', 'Tyler Kolek', 'New York Knicks'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-TS', 'Tyler Smith', 'Milwaukee Bucks'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-TSA', 'Tidjane Salaün', 'Charlotte Hornets'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-TSH', 'Terrence Shannon Jr.', 'Minnesota Timberwolves'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-VW', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-XT', 'Xavier Tillman', 'Boston Celtics'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-YM', 'Yves Missi', 'New Orleans Pelicans'),
  ('Autographs', 'Hoops Hyper Signatures', 'HHS-ZW', 'Ziaire Williams', 'Brooklyn Nets'),
  ('Inserts', 'Bounce House', 'BH-1', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Bounce House', 'BH-2', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Bounce House', 'BH-3', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Bounce House', 'BH-4', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Bounce House', 'BH-5', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Bounce House', 'BH-6', 'Aaron Gordon', 'Denver Nuggets'),
  ('Inserts', 'Bounce House', 'BH-7', 'Shaedon Sharpe', 'Portland Trail Blazers'),
  ('Inserts', 'Bounce House', 'BH-8', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Bounce House', 'BH-9', 'Anthony Davis', 'Dallas Mavericks'),
  ('Inserts', 'Bounce House', 'BH-10', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Bounce House', 'BH-11', 'Donovan Mitchell', 'Cleveland Cavalier'),
  ('Inserts', 'Bounce House', 'BH-12', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Bounce House', 'BH-13', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Bounce House', 'BH-14', 'Zach Lavine', 'Sacramento Kings'),
  ('Inserts', 'Bounce House', 'BH-15', 'Jalen Johnson', 'Atlanta Hawks'),
  ('Inserts', 'Bounce House', 'BH-16', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Bounce House', 'BH-17', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Bounce House', 'BH-18', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Bounce House', 'BH-19', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Bounce House', 'BH-20', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Bounce House', 'BH-21', 'Tre Johnson III', 'Washington Wizards'),
  ('Inserts', 'Bounce House', 'BH-22', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Inserts', 'Bounce House', 'BH-23', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Inserts', 'Bounce House', 'BH-24', 'Asa Newell', 'Atlanta Hawks'),
  ('Inserts', 'Bounce House', 'BH-25', 'Jase Richardson', 'Orlando Magic'),
  ('Inserts', 'Next Episode', 'NE-1', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Next Episode', 'NE-2', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Next Episode', 'NE-3', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Next Episode', 'NE-4', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Next Episode', 'NE-5', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Next Episode', 'NE-6', 'Tre Johnson III', 'Washington Wizards'),
  ('Inserts', 'Next Episode', 'NE-7', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Inserts', 'Next Episode', 'NE-8', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Inserts', 'Next Episode', 'NE-9', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Inserts', 'Next Episode', 'NE-10', 'Khaman Maluach', 'Phoenix Suns'),
  ('Inserts', 'Next Episode', 'NE-11', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Inserts', 'Next Episode', 'NE-12', 'Noa Essengue', 'Chicago Bulls'),
  ('Inserts', 'Next Episode', 'NE-13', 'Derik Queen', 'New Orleans Pelicans'),
  ('Inserts', 'Next Episode', 'NE-14', 'Carter Bryant', 'San Antonio Spurs'),
  ('Inserts', 'Next Episode', 'NE-15', 'Asa Newell', 'Atlanta Hawks'),
  ('Inserts', 'Next Episode', 'NE-16', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Inserts', 'Next Episode', 'NE-17', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Inserts', 'Next Episode', 'NE-18', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Inserts', 'Next Episode', 'NE-19', 'Jase Richardson', 'Orlando Magic'),
  ('Inserts', 'Next Episode', 'NE-20', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Inserts', 'Dunkumentory', 'D-1', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Dunkumentory', 'D-2', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Dunkumentory', 'D-3', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Dunkumentory', 'D-4', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Dunkumentory', 'D-5', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Dunkumentory', 'D-6', 'Vince Carter', 'Toronto Raptors'),
  ('Inserts', 'Dunkumentory', 'D-7', 'Spud Webb', 'Atlanta Hawks'),
  ('Inserts', 'Dunkumentory', 'D-8', 'Dominique Wilkins', 'Atlanta Hawks'),
  ('Inserts', 'Dunkumentory', 'D-9', 'Clyde Drexler', 'Portland Trail Blazers'),
  ('Inserts', 'Dunkumentory', 'D-10', 'Tracy McGrady', 'Orlando Magic'),
  ('Inserts', 'Dunkumentory', 'D-11', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Dunkumentory', 'D-12', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Dunkumentory', 'D-13', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Dunkumentory', 'D-14', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Dunkumentory', 'D-15', 'Khaman Maluach', 'Phoenix Suns'),
  ('Inserts', 'Pay Attention', 'PA-1', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Pay Attention', 'PA-2', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Pay Attention', 'PA-3', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Pay Attention', 'PA-4', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Pay Attention', 'PA-5', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Pay Attention', 'PA-6', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Pay Attention', 'PA-7', 'Donovan Mitchell', 'Cleveland Cavalier'),
  ('Inserts', 'Pay Attention', 'PA-8', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Pay Attention', 'PA-9', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Pay Attention', 'PA-10', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Pay Attention', 'PA-11', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Pay Attention', 'PA-12', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Pay Attention', 'PA-13', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Pay Attention', 'PA-14', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Pay Attention', 'PA-15', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Pay Attention', 'PA-16', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Pay Attention', 'PA-17', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Pay Attention', 'PA-18', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Pay Attention', 'PA-19', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Pay Attention', 'PA-20', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Hoopers', 'H-1', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Hoopers', 'H-2', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Hoopers', 'H-3', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Hoopers', 'H-4', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Hoopers', 'H-5', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Hoopers', 'H-6', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Hoopers', 'H-7', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Hoopers', 'H-8', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Hoopers', 'H-9', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Hoopers', 'H-10', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Hoopers', 'H-11', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Hoopers', 'H-12', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Hoopers', 'H-13', 'Anthony Davis', 'Dallas Mavericks'),
  ('Inserts', 'Hoopers', 'H-14', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Hoopers', 'H-15', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Hoopers', 'H-16', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Hoopers', 'H-17', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Hoopers', 'H-18', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Hoopers', 'H-19', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Hoopers', 'H-20', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Inserts', 'Finals Pursuit', 'FP-1', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-2', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-3', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-4', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Finals Pursuit', 'FP-5', 'Jaren Jackson Jr.', 'Memphis Grizzlies'),
  ('Inserts', 'Finals Pursuit', 'FP-6', 'Scotty Pippen Jr.', 'Memphis Grizzlies'),
  ('Inserts', 'Finals Pursuit', 'FP-7', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-8', 'Aaron Gordon', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-9', 'Jamal Murray', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-10', 'Kawhi Leonard', 'Los Angeles Clippers'),
  ('Inserts', 'Finals Pursuit', 'FP-11', 'James Harden', 'Los Angeles Clippers'),
  ('Inserts', 'Finals Pursuit', 'FP-12', 'Ivica Zubac', 'Los Angeles Clippers'),
  ('Inserts', 'Finals Pursuit', 'FP-13', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Finals Pursuit', 'FP-14', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Finals Pursuit', 'FP-15', 'Austin Reaves', 'Los Angeles Lakers'),
  ('Inserts', 'Finals Pursuit', 'FP-16', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-17', 'Julius Randle', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-18', 'Jaden McDaniels', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-19', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-20', 'Jimmy Butler III', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-21', 'Brandin Podziemski', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-22', 'Amen Thompson', 'Houston Rockets'),
  ('Inserts', 'Finals Pursuit', 'FP-23', 'Jalen Green', 'Houston Rockets'),
  ('Inserts', 'Finals Pursuit', 'FP-24', 'Alperen Sengun', 'Houston Rockets'),
  ('Inserts', 'Finals Pursuit', 'FP-25', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-26', 'Evan Mobley', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-27', 'Darius Garland', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-28', 'Bam Adebayo', 'Miami Heat'),
  ('Inserts', 'Finals Pursuit', 'FP-29', 'Tyler Herro', 'Miami Heat'),
  ('Inserts', 'Finals Pursuit', 'FP-30', 'Davion Mitchell', 'Miami Heat'),
  ('Inserts', 'Finals Pursuit', 'FP-31', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Finals Pursuit', 'FP-32', 'Bobby Portis', 'Milwaukee Bucks'),
  ('Inserts', 'Finals Pursuit', 'FP-33', 'Damian Lillard', 'Milwaukee Bucks'),
  ('Inserts', 'Finals Pursuit', 'FP-34', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-35', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-36', 'Myles Turner', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-37', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Finals Pursuit', 'FP-38', 'Tobias Harris', 'Detroit Pistons'),
  ('Inserts', 'Finals Pursuit', 'FP-39', 'Ausar Thompson', 'Detroit Pistons'),
  ('Inserts', 'Finals Pursuit', 'FP-40', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-41', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-42', 'Mikal Bridges', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-43', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Finals Pursuit', 'FP-44', 'Franz Wagner', 'Orlando Magic'),
  ('Inserts', 'Finals Pursuit', 'FP-45', 'Wendell Carter Jr.', 'Orlando Magic'),
  ('Inserts', 'Finals Pursuit', 'FP-46', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-47', 'Jaylen Brown', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-48', 'Kristaps Porzingis', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-49', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-50', 'Jamal Murray', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-51', 'Michael Porter Jr.', 'Denver Nuggets'),
  ('Inserts', 'Finals Pursuit', 'FP-52', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-53', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-54', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-55', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-56', 'Rudy Gobert', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-57', 'Jonathan Kuminga', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-58', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-59', 'Draymond Green', 'Golden State Warriors'),
  ('Inserts', 'Finals Pursuit', 'FP-60', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-61', 'Andrew Nembhard', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-62', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-63', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-64', 'Evan Mobley', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-65', 'Jarrett Allen', 'Cleveland Cavaliers'),
  ('Inserts', 'Finals Pursuit', 'FP-66', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-67', 'Jaylen Brown', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-68', 'Derrick White', 'Boston Celtics'),
  ('Inserts', 'Finals Pursuit', 'FP-69', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-70', 'OG Anunoby', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-71', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-72', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-73', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-74', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-75', 'Donte Divencenzo', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-76', 'Jaden McDaniels', 'Minnesota Timberwolves'),
  ('Inserts', 'Finals Pursuit', 'FP-77', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-78', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-79', 'Mikal Bridges', 'New York Knicks'),
  ('Inserts', 'Finals Pursuit', 'FP-80', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-81', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-82', 'Obi Toppin', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-83', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-84', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-85', 'T.J. McConnell', 'Indiana Pacers'),
  ('Inserts', 'Finals Pursuit', 'FP-86', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-87', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-88', 'Alex Caruso', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-89', 'Oklahoma City Thunder', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-90', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-91', 'Chet Holmgren', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-92', 'Luguentz Dort', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-93', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-94', 'Alex Caruso', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-95', 'Isaiah Hartenstein', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-96', 'Cason Wallace', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-97', 'Kenrich Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-98', 'Aaron Wiggins', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-99', 'Ajay Mitchell', 'Oklahoma City Thunder'),
  ('Inserts', 'Finals Pursuit', 'FP-100', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Oasis', 'O-1', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Oasis', 'O-2', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Oasis', 'O-3', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Oasis', 'O-4', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Oasis', 'O-5', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Oasis', 'O-6', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Oasis', 'O-7', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Oasis', 'O-8', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Oasis', 'O-9', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Oasis', 'O-10', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Oasis', 'O-11', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Oasis', 'O-12', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Oasis', 'O-13', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Oasis', 'O-14', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Oasis', 'O-15', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Inserts', 'Oasis', 'O-16', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Oasis', 'O-17', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Oasis', 'O-18', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Oasis', 'O-19', 'Bam Adebayo', 'Miami Heat'),
  ('Inserts', 'Oasis', 'O-20', 'Trae Young', 'Atlanta Hawks'),
  ('Inserts', 'Oasis', 'O-21', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Oasis', 'O-22', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Oasis', 'O-23', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Oasis', 'O-24', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Oasis', 'O-25', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Inserts', 'Joy', 'JOY-1', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Joy', 'JOY-2', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Joy', 'JOY-3', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Joy', 'JOY-4', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Joy', 'JOY-5', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Joy', 'JOY-6', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Joy', 'JOY-7', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Joy', 'JOY-8', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Joy', 'JOY-9', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Joy', 'JOY-10', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Checkmate', 'C-1', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Checkmate', 'C-2', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Checkmate', 'C-3', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Checkmate', 'C-4', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Checkmate', 'C-5', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Checkmate', 'C-6', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Checkmate', 'C-7', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Checkmate', 'C-8', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Checkmate', 'C-9', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Checkmate', 'C-10', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Checkmate', 'C-11', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Checkmate', 'C-12', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Checkmate', 'C-13', 'Anthony Davis', 'Dallas Mavericks'),
  ('Inserts', 'Checkmate', 'C-14', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Checkmate', 'C-15', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Checkmate', 'C-16', 'Brandon Miller', 'Charlotte Hornets'),
  ('Inserts', 'Checkmate', 'C-17', 'Trae Young', 'Atlanta Hawks'),
  ('Inserts', 'Checkmate', 'C-18', 'Kawhi Leonard', 'Los Angeles Clippers'),
  ('Inserts', 'Checkmate', 'C-19', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Checkmate', 'C-20', 'Bam Adebayo', 'Miami Heat'),
  ('Inserts', 'Checkmate', 'C-21', 'Darius Garland', 'Cleveland Cavaliers'),
  ('Inserts', 'Checkmate', 'C-22', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Checkmate', 'C-23', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Inserts', 'Checkmate', 'C-24', 'Tyrese Maxey', 'Philadelphia 76ers'),
  ('Inserts', 'Checkmate', 'C-25', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Checkmate', 'C-26', 'Jalen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Checkmate', 'C-27', 'Jaylen Brown', 'Boston Celtics'),
  ('Inserts', 'Checkmate', 'C-28', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Checkmate', 'C-29', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Inserts', 'Checkmate', 'C-30', 'LaMelo Ball', 'Charlotte Hornets'),
  ('Inserts', 'Hoopnotic', 'HN-1', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Hoopnotic', 'HN-2', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Hoopnotic', 'HN-3', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Hoopnotic', 'HN-4', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Hoopnotic', 'HN-5', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Hoopnotic', 'HN-6', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Hoopnotic', 'HN-7', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Hoopnotic', 'HN-8', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Hoopnotic', 'HN-9', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Hoopnotic', 'HN-10', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Hoopnotic', 'HN-11', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Hoopnotic', 'HN-12', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Hoopnotic', 'HN-13', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Hoopnotic', 'HN-14', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Hoopnotic', 'HN-15', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Hoopnotic', 'HN-16', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Hoopnotic', 'HN-17', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Inserts', 'Hoopnotic', 'HN-18', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Hoopnotic', 'HN-19', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Hoopnotic', 'HN-20', 'James Harden', 'Los Angeles Clippers'),
  ('Inserts', 'Hoopnotic', 'HN-21', 'Dirk Nowitzki', 'Dallas Mavericks'),
  ('Inserts', 'Hoopnotic', 'HN-22', 'Allen Iverson', 'Philadelphia 76ers'),
  ('Inserts', 'Hoopnotic', 'HN-23', 'Shaquille O''Neal', 'Los Angeles Lakers'),
  ('Inserts', 'Hoopnotic', 'HN-24', 'Kevin Garnett', 'Minnesota Timberwolves'),
  ('Inserts', 'Hoopnotic', 'HN-25', 'Larry Bird', 'Boston Celtics'),
  ('Inserts', 'Hoopnotic', 'HN-26', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Hoopnotic', 'HN-27', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Hoopnotic', 'HN-28', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Hoopnotic', 'HN-29', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Hoopnotic', 'HN-30', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Hoopnotic', 'HN-31', 'Tre Johnson III', 'Washington Wizards'),
  ('Inserts', 'Hoopnotic', 'HN-32', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Inserts', 'Hoopnotic', 'HN-33', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Inserts', 'Hoopnotic', 'HN-34', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Inserts', 'Hoopnotic', 'HN-35', 'Khaman Maluach', 'Phoenix Suns'),
  ('Inserts', 'Hardwired', 'HW-1', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Hardwired', 'HW-2', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Hardwired', 'HW-3', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Hardwired', 'HW-4', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Hardwired', 'HW-5', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Hardwired', 'HW-6', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Hardwired', 'HW-7', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Hardwired', 'HW-8', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Hardwired', 'HW-9', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Hardwired', 'HW-10', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Hardwired', 'HW-11', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Hardwired', 'HW-12', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Hardwired', 'HW-13', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Hardwired', 'HW-14', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Hardwired', 'HW-15', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Hardwired', 'HW-16', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Hardwired', 'HW-17', 'Anthony Davis', 'Dallas Mavericks'),
  ('Inserts', 'Hardwired', 'HW-18', 'Evan Mobley', 'Cleveland Cavaliers'),
  ('Inserts', 'Hardwired', 'HW-19', 'De''Aaron Fox', 'San Antonio Spurs'),
  ('Inserts', 'Hardwired', 'HW-20', 'Tyrese Maxey', 'Philadelphia 76ers'),
  ('Inserts', 'Hardwired', 'HW-21', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Hardwired', 'HW-22', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Hardwired', 'HW-23', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Hardwired', 'HW-24', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Hardwired', 'HW-25', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'The Buzz', 'TB-1', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'The Buzz', 'TB-2', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'The Buzz', 'TB-3', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'The Buzz', 'TB-4', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'The Buzz', 'TB-5', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'The Buzz', 'TB-6', 'Tre Johnson III', 'Washington Wizards'),
  ('Inserts', 'The Buzz', 'TB-7', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Inserts', 'The Buzz', 'TB-8', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Inserts', 'The Buzz', 'TB-9', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Inserts', 'The Buzz', 'TB-10', 'Khaman Maluach', 'Phoenix Suns'),
  ('Inserts', 'The Buzz', 'TB-11', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Inserts', 'The Buzz', 'TB-12', 'Noa Essengue', 'Chicago Bulls'),
  ('Inserts', 'The Buzz', 'TB-13', 'Derik Queen', 'New Orleans Pelicans'),
  ('Inserts', 'The Buzz', 'TB-14', 'Carter Bryant', 'San Antonio Spurs'),
  ('Inserts', 'The Buzz', 'TB-15', 'Thomas Sorber', 'Oklahoma City Thunder'),
  ('Inserts', 'The Buzz', 'TB-16', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Inserts', 'The Buzz', 'TB-17', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Inserts', 'The Buzz', 'TB-18', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Inserts', 'The Buzz', 'TB-19', 'Nolan Traore', 'Brooklyn Nets'),
  ('Inserts', 'The Buzz', 'TB-20', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Inserts', 'The Buzz', 'TB-21', 'Will Riley', 'Washington Wizards'),
  ('Inserts', 'The Buzz', 'TB-22', 'Drake Powell', 'Brooklyn Nets'),
  ('Inserts', 'The Buzz', 'TB-23', 'Asa Newell', 'Atlanta Hawks'),
  ('Inserts', 'The Buzz', 'TB-24', 'Nique Clifford', 'Sacramento Kings'),
  ('Inserts', 'The Buzz', 'TB-25', 'Jase Richardson', 'Orlando Magic'),
  ('Inserts', 'The Buzz', 'TB-26', 'Ben Saraf', 'Brooklyn Nets'),
  ('Inserts', 'The Buzz', 'TB-27', 'Danny Wolf', 'Brooklyn Nets'),
  ('Inserts', 'The Buzz', 'TB-28', 'Hugo González', 'Boston Celtics'),
  ('Inserts', 'The Buzz', 'TB-29', 'Liam Mcneeley', 'Charlotte Hornets'),
  ('Inserts', 'The Buzz', 'TB-30', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Inserts', 'Net 2 Net', 'NTN-1', 'Bam Adebayo', 'Miami Heat'),
  ('Inserts', 'Net 2 Net', 'NTN-2', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Net 2 Net', 'NTN-3', 'LaMelo Ball', 'Charlotte Hornets'),
  ('Inserts', 'Net 2 Net', 'NTN-4', 'Paolo Banchero', 'Orlando Magic'),
  ('Inserts', 'Net 2 Net', 'NTN-5', 'Devin Booker', 'Phoenix Suns'),
  ('Inserts', 'Net 2 Net', 'NTN-6', 'Jaylen Brown', 'Boston Celtics'),
  ('Inserts', 'Net 2 Net', 'NTN-7', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Net 2 Net', 'NTN-8', 'Cade Cunningham', 'Detroit Pistons'),
  ('Inserts', 'Net 2 Net', 'NTN-9', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Net 2 Net', 'NTN-10', 'Anthony Davis', 'Dallas Mavericks'),
  ('Inserts', 'Net 2 Net', 'NTN-11', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Net 2 Net', 'NTN-12', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Net 2 Net', 'NTN-13', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Net 2 Net', 'NTN-14', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Net 2 Net', 'NTN-15', 'Tyrese Haliburton', 'Indiana Pacers'),
  ('Inserts', 'Net 2 Net', 'NTN-16', 'Kyrie Irving', 'Dallas Mavericks'),
  ('Inserts', 'Net 2 Net', 'NTN-17', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Net 2 Net', 'NTN-18', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Net 2 Net', 'NTN-19', 'Kawhi Leonard', 'Los Angeles Clippers'),
  ('Inserts', 'Net 2 Net', 'NTN-20', 'Tyrese Maxey', 'Philadelphia 76ers'),
  ('Inserts', 'Net 2 Net', 'NTN-21', 'Brandon Miller', 'Charlotte Hornets'),
  ('Inserts', 'Net 2 Net', 'NTN-22', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Net 2 Net', 'NTN-23', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Net 2 Net', 'NTN-24', 'Domantas Sabonis', 'Sacramento Kings'),
  ('Inserts', 'Net 2 Net', 'NTN-25', 'Pascal Siakam', 'Indiana Pacers'),
  ('Inserts', 'Net 2 Net', 'NTN-26', 'Jayson Tatum', 'Boston Celtics'),
  ('Inserts', 'Net 2 Net', 'NTN-27', 'Karl-Anthony Towns', 'New York Knicks'),
  ('Inserts', 'Net 2 Net', 'NTN-28', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Net 2 Net', 'NTN-29', 'Jaylen Williams', 'Oklahoma City Thunder'),
  ('Inserts', 'Net 2 Net', 'NTN-30', 'Trae Young', 'Atlanta Hawks'),
  ('Inserts', 'Jam Packed', 'JP-1', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Jam Packed', 'JP-2', 'Ja Morant', 'Memphis Grizzlies'),
  ('Inserts', 'Jam Packed', 'JP-3', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Jam Packed', 'JP-4', 'LeBron James', 'Los Angeles Lakers'),
  ('Inserts', 'Jam Packed', 'JP-5', 'Obi Toppin', 'Indiana Pacers'),
  ('Inserts', 'Jam Packed', 'JP-6', 'Donovan Mitchell', 'Cleveland Cavaliers'),
  ('Inserts', 'Jam Packed', 'JP-7', 'Aaron Gordon', 'Denver Nuggets'),
  ('Inserts', 'Jam Packed', 'JP-8', 'Zach lavine', 'Sacramento Kings'),
  ('Inserts', 'Jam Packed', 'JP-9', 'Shaedon Sharpe', 'Portland Trail Blazers'),
  ('Inserts', 'Jam Packed', 'JP-10', 'Derrick Jones Jr.', 'Los Angeles Clippers'),
  ('Inserts', 'Jam Packed', 'JP-11', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Jam Packed', 'JP-12', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Jam Packed', 'JP-13', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Jam Packed', 'JP-14', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Inserts', 'Jam Packed', 'JP-15', 'Asa Newell', 'Atlanta Hawks'),
  ('Inserts', 'Block By Block', 'BYB-1', 'Cooper Flagg', 'Dallas Mavericks'),
  ('Inserts', 'Block By Block', 'BYB-2', 'Dylan Harper', 'San Antonio Spurs'),
  ('Inserts', 'Block By Block', 'BYB-3', 'VJ Edgecombe', 'Philadelphia 76ers'),
  ('Inserts', 'Block By Block', 'BYB-4', 'Kon Knueppel', 'Charlotte Hornets'),
  ('Inserts', 'Block By Block', 'BYB-5', 'Ace Bailey', 'Utah Jazz'),
  ('Inserts', 'Block By Block', 'BYB-6', 'Tre Johnson III', 'Washington Wizards'),
  ('Inserts', 'Block By Block', 'BYB-7', 'Jeremiah Fears', 'New Orleans Pelicans'),
  ('Inserts', 'Block By Block', 'BYB-8', 'Egor Dëmin', 'Brooklyn Nets'),
  ('Inserts', 'Block By Block', 'BYB-9', 'Collin Murray-Boyles', 'Toronto Raptors'),
  ('Inserts', 'Block By Block', 'BYB-10', 'Khaman Maluach', 'Phoenix Suns'),
  ('Inserts', 'Block By Block', 'BYB-11', 'Cedric Coward', 'Memphis Grizzlies'),
  ('Inserts', 'Block By Block', 'BYB-12', 'Noa Essengue', 'Chicago Bulls'),
  ('Inserts', 'Block By Block', 'BYB-13', 'Derik Queen', 'New Orleans Pelicans'),
  ('Inserts', 'Block By Block', 'BYB-14', 'Carter Bryant', 'San Antonio Spurs'),
  ('Inserts', 'Block By Block', 'BYB-15', 'Thomas Sorber', 'Oklahoma City Thunder'),
  ('Inserts', 'Block By Block', 'BYB-16', 'Yang Hansen', 'Portland Trail Blazers'),
  ('Inserts', 'Block By Block', 'BYB-17', 'Joan Beringer', 'Minnesota Timberwolves'),
  ('Inserts', 'Block By Block', 'BYB-18', 'Walter Clayton Jr.', 'Utah Jazz'),
  ('Inserts', 'Block By Block', 'BYB-19', 'Nolan Traore', 'Brooklyn Nets'),
  ('Inserts', 'Block By Block', 'BYB-20', 'Kasparas Jakučionis', 'Miami Heat'),
  ('Inserts', 'Block By Block', 'BYB-21', 'Will Riley', 'Washington Wizards'),
  ('Inserts', 'Block By Block', 'BYB-22', 'Drake Powell', 'Brooklyn Nets'),
  ('Inserts', 'Block By Block', 'BYB-23', 'Asa Newell', 'Atlanta Hawks'),
  ('Inserts', 'Block By Block', 'BYB-24', 'Nique Clifford', 'Sacramento Kings'),
  ('Inserts', 'Block By Block', 'BYB-25', 'Jase Richardson', 'Orlando Magic'),
  ('Inserts', 'Block By Block', 'BYB-26', 'Ben Saraf', 'Brooklyn Nets'),
  ('Inserts', 'Block By Block', 'BYB-27', 'Danny Wolf', 'Brooklyn Nets'),
  ('Inserts', 'Block By Block', 'BYB-28', 'Hugo González', 'Boston Celtics'),
  ('Inserts', 'Block By Block', 'BYB-29', 'Liam Mcneeley', 'Charlotte Hornets'),
  ('Inserts', 'Block By Block', 'BYB-30', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers'),
  ('Inserts', 'Block By Block', 'BYB-31', 'Rasheer Fleming', 'Phoenix Suns'),
  ('Inserts', 'Block By Block', 'BYB-32', 'Noah Penda', 'Orlando Magic'),
  ('Inserts', 'Block By Block', 'BYB-33', 'Sion James', 'Charlotte Hornets'),
  ('Inserts', 'Block By Block', 'BYB-34', 'Ryan Kalkbrenner', 'Charlotte Hornets'),
  ('Inserts', 'Block By Block', 'BYB-35', 'Johni Broome', 'Philadelphia 76ers'),
  ('Inserts', 'Block By Block', 'BYB-36', 'Adou Thiero', 'Los Angeles Lakers'),
  ('Inserts', 'Block By Block', 'BYB-37', 'Chaz Lanier', 'Detroit Pistons'),
  ('Inserts', 'Block By Block', 'BYB-38', 'Kam Jones', 'Indiana Pacers'),
  ('Inserts', 'Block By Block', 'BYB-39', 'Alijah Martin', 'Toronto Raptors'),
  ('Inserts', 'Block By Block', 'BYB-40', 'Maxime Raynaud', 'Sacramento Kings'),
  ('Inserts', 'Boom Shaka Laka', 'BO-1', 'Nikola Jokić', 'Denver Nuggets'),
  ('Inserts', 'Boom Shaka Laka', 'BO-2', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder'),
  ('Inserts', 'Boom Shaka Laka', 'BO-3', 'Luka Dončić', 'Los Angeles Lakers'),
  ('Inserts', 'Boom Shaka Laka', 'BO-4', 'Giannis Antetokounmpo', 'Milwaukee Bucks'),
  ('Inserts', 'Boom Shaka Laka', 'BO-5', 'Stephen Curry', 'Golden State Warriors'),
  ('Inserts', 'Boom Shaka Laka', 'BO-6', 'Anthony Edwards', 'Minnesota Timberwolves'),
  ('Inserts', 'Boom Shaka Laka', 'BO-7', 'Jalen Brunson', 'New York Knicks'),
  ('Inserts', 'Boom Shaka Laka', 'BO-8', 'Victor Wembanyama', 'San Antonio Spurs'),
  ('Inserts', 'Boom Shaka Laka', 'BO-9', 'Kevin Durant', 'Houston Rockets'),
  ('Inserts', 'Boom Shaka Laka', 'BO-10', 'Cooper Flagg', 'Dallas Mavericks')
) as seed(category, subset, card_number, player_name, team_name)
on conflict (set_id, card_number, subset) do update
  set category = excluded.category,
      player_name = excluded.player_name,
      team_name = excluded.team_name;

commit;
